import type { NextPage } from "next";
import Head from "next/head";
import ArrowBtn from "@/components/lib/ArrowBtn";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>audiophile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./public/favicon-32x32.png" />
      </Head>

      <main className="bg-101010">
        <h1>Audiofile app</h1>
        <button className="btn-gold">See Products</button>
        <button className="btn-white">See Products</button>
        <ArrowBtn action="Shop" link="/" />
      </main>
    </div>
  );
};

export default Home;
