import type { NextPage } from "next";
import Head from "next/head";
import ArrowBtn from "@/components/lib/ArrowBtn";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Audiofile app</h1>
      </main>
      <button className="btn-gold">See Products</button>
      <button className="btn-white">See Products</button>
      <ArrowBtn action="Shop" link="/" />
    </div>
  );
};

export default Home;
